name: Purge Cloudflare Cache pe Push

on:
  push:
    branches:
      - main
      - master

      
jobs:
  purge-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Trimitere comanda Purge Everything catre Cloudflare
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
               -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
               -H "Content-Type: application/json" \
               --data '{"purge_everything":true}'